### ISSUE TITLE
The GitHub button is barely visible on Dark Mode

### ISSUE THREAD

**Issue by KSXGitHub** [pnpm/pnpm.github.io#112]
![screenshot of https://pnpm.io/ on Dark Mode with a black GitHub icon red-circled](https://user-images.githubusercontent.com/11488886/118750036-dd222e80-b888-11eb-8ba1-eff979edd193.png)

**Comment by ltdu** [comment]
This is now fixed:

![image](https://user-images.githubusercontent.com/22098043/132064885-b276402b-03e2-49ef-a94b-2c45c40a1c72.png)
