### ISSUE TITLE
Create a "Community" section

### ISSUE THREAD

**Issue by zkochan** [pnpm/pnpm.github.io#116]
Make a community section with links to articles and talks about pnpm.

Similar to https://reactjs.org/community/support.html or https://docusaurus.io/community/support. The links should be take from https://github.com/pnpm/awesome-pnpm

Blocked until https://github.com/facebook/docusaurus/issues/3810 is fixed in docusaurus.

**Comment by olrtg** [comment]
Hey @zkochan [facebook/docusaurus#3810](https://github.com/facebook/docusaurus/issues/3810) seems to be closed now!
I will like to send a PR for this. Can i proceed with this or do we need to update docusaurus first?

**Comment by olrtg** [comment]
Oh! nevermind. This is done already. Can we close this?

**Comment by juanpicado** [comment]
@olrtg go ahead ! Here Zoltan describe what he was willling to do https://github.com/pnpm/pnpm.github.io/pull/150#issuecomment-968133293

**Comment by olrtg** [comment]
Hi @juanpicado ! Ok, i'm going to work on this then.
Litte noobie question, how can i submit the changes to this existing PR (#150 )(i don't know if creating a new PR is a good thing in this case)

**Comment by juanpicado** [comment]
I'd create a new one if @zkochan does not mind, one option is `git cherry pick` that commit (it's only one anyway). If you need help ping me over Discord pnpm channel (we have spanish channel as well) or we can continue here.

**Comment by zkochan** [comment]
I don't care if you create a new pr

**Comment by olrtg** [comment]
Thanks for the quick reply guys!
I'm going to take a look at this in a few hours.

**Comment by olrtg** [comment]
@zkochan How should we implement this? i wanted to add a sidebar to the page but [docusaurus pages do not have sidebars](https://docusaurus.io/docs/creating-pages).
Should we just add links to the subpages in a list?

**Comment by zkochan** [comment]
They have sidebars. We use sidebars in the docs. See how sidebars are also here: https://docusaurus.io/community/support
