### ISSUE TITLE
The website looks weird on tablet

### ISSUE THREAD

**Issue by krishguptadev** [pnpm/pnpm.github.io#155]
![image](https://user-images.githubusercontent.com/91655303/139247095-049d49fb-03a5-48d9-9a2f-bf9b435d462a.png)
![image](https://user-images.githubusercontent.com/91655303/139247100-a7d451b2-2a14-4b18-b40c-0d722e319597.png)
![image](https://user-images.githubusercontent.com/91655303/139247102-8cf8591c-351f-4db0-9ea2-dcdcc56192f1.png)

**Comment by juanpicado** [comment]
:) I still not sure if follow correctly, maybe you could try describe better so I can have a better idea what you consider weird or even better a suggestion how should looks like so I can potentially improve it.

**Comment by krishguptadev** [comment]
> :) I still not sure if follow correctly, maybe you could try describe better so I can have a better idea what you consider weird or even better a suggestion how should looks like so I can potentially improve it.

If the icon is aligned to the center, the text should be too...
