### ISSUE TITLE
Examples of package dependencies with "@" signs shown as "[email protected]"

### ISSUE THREAD

**Issue by moll** [pnpm/pnpm.github.io#178]
Hey,

I suspect this is Cloudflare going haywire on the website, but the fact is, all or most examples in the form of `package@1.2.3` are rendered as `[email protected]`. For example, on https://pnpm.io/workspaces, this is how the text is rendered:

> By default, pnpm will link packages from the workspace if the available packages match the declared ranges. For instance, [email protected] is linked into bar if bar has "foo": "^1.0.0" in its dependencies. However, if bar has "foo": "2.0.0" in dependencies and [email protected] is not in the workspace, [email protected] will be installed from the registry. This behavior introduces some uncertainty.

This can even be confirmed with `curl https://pnpm.io/workspaces` — package version examples are `[email protected]` even in the source.

Cheers

**Comment by zkochan** [comment]
I turned off this rule in CloudFlare

![image](https://user-images.githubusercontent.com/1927579/143645463-6082951f-934b-4438-bd8f-4195db23b398.png)

**Comment by moll** [comment]
Seems to have fixed it! Thanks.
