### ISSUE TITLE
Documentation for `-w` (or `--workspace-root`) is not clear

### ISSUE THREAD

**Issue by LSViana** [pnpm/pnpm.github.io#187]
It's my first time reading the documentation for pnpm and when I stumbled upon this:

> Run as if pnpm was started in the root of the workspace instead of the current working directory.

In the section of "[-w, --workspace-root](https://pnpm.io/pnpm-cli#-w---workspace-root)", it was not clear to me what type of "workspace" is being referred to there. Is it a VS Code workspace?

Maybe it could be explicitly said that it's a VS Code workspace or something similar.

**Comment by LSViana** [comment]
Should that documentation portion be linking to [workspaces](https://pnpm.io/workspaces) page?

**Comment by zkochan** [comment]
The root of the workspace is the folder that has the `pnpm-workspace.yaml` file. Basically, it is the root of the repository.

**Comment by LSViana** [comment]
@zkochan I discovered it later when reading the documentation.

But, in any case, it wouldn't do any harm to add mentions to that page whenever "workspaces" are mentioned, right? It's hard to know what page exactly someone new to the project will land (being completely unaware of these key terms).

If you'd like it, I can submit a PR. 😃

**Comment by zkochan** [comment]
Sure. I have no objections
