### ISSUE TITLE
PNPM can now be installed using Scoop on Windows

### ISSUE THREAD

**Issue by T145** [pnpm/pnpm.github.io#210]
https://github.com/ScoopInstaller/Main/issues/3177

I'd recommend the following command:
```
scoop install node-lts pnpm
```

**Comment by olrtg** [comment]
Nice!
I would like to make a PR of this.

**Comment by olrtg** [comment]
Hey @zkochan thanks for merging this! Also excuse my formatter >:c

**Comment by JustinGrote** [comment]
@zkochan  @T145 the scoop installer doesn't work with `pnpm env use`, does it need to be updated?
![image](https://user-images.githubusercontent.com/15258962/227329964-ab7ea750-5dcd-407d-b23d-89a1631e9a5c.png)
