### ISSUE TITLE
docs in spanish language

### ISSUE THREAD

**Issue by olrtg** [pnpm/pnpm.github.io#215]
Hey guys! i would like to start translating the docs to spanish.
Are you interested on this type of stuff? And also how can we move forward?

I am a native spanish speaker.

**Comment by juanpicado** [comment]
Yes, you can start here https://crowdin.com/project/pnpm I did some progress time ago but help is very welcome.

**Comment by olrtg** [comment]
Hey @juanpicado ! thanks for the reply.
Okay I'll be working on this then.
One question.. when you do the translation, those changes are instantly visible or should i do something else?

**Comment by zkochan** [comment]
The translations on the website only appear after a deployment.

**Comment by zkochan** [comment]
you can close the issue if you want

approval is not necessary
