### ISSUE TITLE
nodejs-lts instead of node-lts

### ISSUE THREAD

**Issue by MonoLogueChi** [pnpm/pnpm.github.io#219]
#210 
Use the scoop installation command to be 

```
scoop install nodejs-lts pnpm
```
 but not

```
scoop install node-lts pnpm
```

**Comment by zkochan** [comment]
What is the difference between the two?

**Comment by MonoLogueChi** [comment]
> What is the difference between the two?

Scoop No package node-lts, the result of execution will be `Couldn't find manifest for 'node-lts'.`
