### ISSUE TITLE
"Access Denied"?

### ISSUE THREAD

**Issue by andre4ik3** [pnpm/pnpm.github.io#266]
Hello,

I am unable to access the pnpm website due to what looks to be a Cloudflare misconfiguration? I was looking for alternatives to Yarn since v1 is "legacy" and pnpm looks cool, however I am completely unable to access the website. Below is a screenshot:

<img width="1109" alt="Снимок экрана 2022-05-21 в 22 09 48" src="https://user-images.githubusercontent.com/62390580/169666071-e443e9dd-4157-48ec-af18-1eade20a21d5.png">

Could you please check your Cloudflare security policies? Perhaps I've tripped up some sort of bot filter?

Best regards,
andre4ik3

**Comment by zkochan** [comment]
I live in Ukraine. I have blocked traffic from Belarus and Russia.

If you support Ukraine, feel free to use a VPN to access the website.

**Comment by andre4ik3** [comment]
Ok.
