### ISSUE TITLE
Confusing code example

### ISSUE THREAD

**Issue by limichange** [pnpm/pnpm.github.io#271]
In the section, the code is `https://get.pnpm.io/v6.16.js`, should it be `https://get.pnpm.io/v7.1.js`? In fact, the code is working right, i just a little confused it.

## link
https://pnpm.io/cli/fetch#usage-scenario

## code
```
FROM node:14

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

# pnpm fetch does require only lockfile
COPY pnpm-lock.yaml ./

RUN pnpm fetch --prod


ADD . ./
RUN pnpm install -r --offline --prod


EXPOSE 8080
CMD [ "node", "server.js" ]
```

**Comment by zkochan** [comment]
It installs the latest pnpm version using pnpm v6.16
