### ISSUE TITLE
ERR_PNPM_OUTDATED_LOCKFILE not described

### ISSUE THREAD

**Issue by pitgrap** [pnpm/pnpm.github.io#299]
In the docs for error codes (https://pnpm.io/errors) ERR_PNPM_OUTDATED_LOCKFILE  is not listed and described and the search has no results.

Please list all error codes on https://pnpm.io/errors and describe and/or link them to the according documentation.

**Comment by zkochan** [comment]
I don't have objections but this particular error has a lot of details in the console output.
