### ISSUE TITLE
:|

### ISSUE THREAD

**Issue by babakfp** [pnpm/pnpm.github.io#314]
![Screenshot 2022-09-04 093915](https://user-images.githubusercontent.com/44144724/188324301-a7db3986-596b-4cca-81d7-b9fd94c83e04.png)

**Comment by juanpicado** [comment]
Works for me, try on terminal.

**Comment by babakfp** [comment]
Don't close the issue if it's not resolved! :|
It's the same thing. The terminal doesn't do magic! (I tried it).
