### ISSUE TITLE
Project Not Found - Crowdin

### ISSUE THREAD

**Issue by yfdyh000** [pnpm/pnpm.github.io#32]
https://crowdin.com/project/pnpm are 404.

In addition, Language - Chinese (中文) seems to be ineffective.

**Comment by juanpicado** [comment]
@zkochan I was wondering the same, does the crowdin project actually exist? I can help to set it up in such case.

**Comment by zkochan** [comment]
It did exist. I'll have to look into it.

**Comment by rmaycon** [comment]
ok

Em sex, 14 de jun de 2019 às 04:29, Zoltan Kochan <notifications@github.com>
escreveu:

**Comment by juanpicado** [comment]
I think :-) this can be closed

**Comment by zkochan** [comment]
So seems like crowdin had some update and they converted the pnpm project to private. I have changed it back to public. Also, I requested a free account. They gave it to us.

Now I need to figure out how to upload the Portuguese translation. For some reason, the crowdin CLI only uploads the English translation at the moment
