### ISSUE TITLE
How to define popular in workspaces?

### ISSUE THREAD

**Issue by moonrailgun** [pnpm/pnpm.github.io#342]
Hi, Its looks like filter *popular* project in pnpm workspace showcase.(in https://pnpm.io/workspaces)

Is any definition about `popular`? Because i am very like pnpm and hope my repo can show in this platform(its my dream :) )

Thanks for your pnpm :)

**Comment by zkochan** [comment]
The list of projects is already long. So I don't think we will add more projects to it. If there is a project with more stars than one of the projects in the list, then we will include it and remove one from the list.

**Comment by moonrailgun** [comment]
> The list of projects is already long. So I don't think we will add more projects to it. If there is a project with more stars than one of the projects in the list, then we will include it and remove one from the list.

Get it. Thanks for your reply
