### ISSUE TITLE
Why does section on Changesets recommend using changeset publish in Github action?

### ISSUE THREAD

**Issue by justintemps** [pnpm/pnpm.github.io#354]
Why does this line in the [changeset docs](https://pnpm.io/using-changesets) recommend calling a script that uses `changeset publish` instead of `pnpm publish -r`?

https://github.com/pnpm/pnpm.github.io/blob/865410bb9629e4caf06c2b9e60e71be3aad4cc6e/docs/using-changesets.md?plain=1#L54

I ask because it seems like changests has issues correctly replacing `workspace:*` version ranges with the appropriate version from the associated package. I'm citing this [comment here](https://github.com/changesets/changesets/issues/432#issuecomment-668793908) and it's not clear to me from subsequent threads and my own experience that this has changed.

I'm having some issues with this in a current project and was wondering what what substantively `changeset publish` does different than `pnpm publish -r` in the context of the [Changeset Github Action](https://github.com/changesets/action)?

**Comment by zkochan** [comment]
I don't know why. We use `pnpm publish -r` in the pnpm monorepo. I think @juanpicado wrote that page.

**Comment by juanpicado** [comment]
I´m using https://github.com/verdaccio/verdaccio/blob/master/.github/workflows/changesets.yml#L63 but I´m don´t have on my dependencies `workspace:*` to be honest and I'm not having that issue, maybe rely better on pnpm publish to avoid issues.

**Comment by juanpicado** [comment]
We should merge this then https://github.com/pnpm/pnpm.github.io/pull/322 😊

**Comment by justintemps** [comment]
In my case, it turned out to be that a stray yarn.lock file had snuck into that package and Changests was intuiting that I wanted to use yarn to publish instead of pnpm (I think because of the logic in [preferred-pm](https://github.com/zkochan/packages/tree/master/preferred-pm)).

Removing the yarn.lock file, which shouldn't have been there anyway, solved the issue.

However, if `changeset publish` isn't doing anything different than detecting that you want to run `pnpm publish -r` and then doing it, then it might be clearer for users to just have `pnpm publish -r` in the docs.

**Comment by juanpicado** [comment]
Ok, I'll start using `pnpm publish -r` I want to see if the experience is positive (I release often) and also merge #322 thanks for raising this issue @justintemps
