### ISSUE TITLE
Suggest `brew install corepack` for Homebrew users

### ISSUE THREAD

**Issue by andersk** [pnpm/pnpm.github.io#359]
The [installation guide](https://pnpm.io/installation#using-corepack) correctly says that

> Since v16.13, Node.js is shipping [Corepack](https://nodejs.org/api/corepack.html) for managing package managers.

However, macOS users who installed Node.js from Homebrew may be slightly misled here, since Homebrew splits corepack into a separate [formula](https://formulae.brew.sh/formula/corepack) ([discussion](https://github.com/Homebrew/discussions/discussions/2348)). It may be worth pointing out that Homebrew users need to run `brew install corepack`.

(Of course, Homebrew users can also scroll down and find they can `brew install pnpm` directly, but then they won’t benefit from Corepack’s automatic [`packageManager`](https://nodejs.org/api/packages.html#packagemanager) version selection.)

**Comment by zkochan** [comment]
I did know this. Yes, let's add this to the docs.

**Comment by karlhorky** [comment]
Hmm... it seems to be installed for me, without installing `corepack` itself:

```bash
$ brew upgrade corepack
Error: corepack not installed
$ ls -al $(which corepack)
lrwxr-xr-x  1 k  admin    38B Feb 18 15:02 /opt/homebrew/bin/corepack -> ../Cellar/node@18/18.14.1/bin/corepack
```

@andersk @zkochan Maybe 84fc97dc812f63e08d12cf223cc187bfbcfa2b4e should be reverted?
