### ISSUE TITLE
example config for CircleCI

### ISSUE THREAD

**Issue by NicoWeio** [pnpm/pnpm.github.io#36]
I suggest adding an example config.yml to [the docs](https://pnpm.js.org/docs/en/continuous-integration.html).

**Comment by joeldenning** [comment]
For anybody still looking for this, here's a repo that is successfully using pnpm + CircleCI. I authored it and don't know if there's a better way to do things, but sharing here in case it helps:

https://github.com/react-microfrontends/navbar/blob/master/.circleci/config.yml

**Comment by CrazyOptimist** [comment]
I was able to figure it out using `sudo` with the standard CircleCI `cimg/node:14.7` image.
Like `run: sudo npm install --global pnpm typescript` and `pnpm install --frozen-lockfile`.
Please advice if you find something wrong in doing like this.
Hope it helps!

**Comment by juanpicado** [comment]
Seems fixed https://github.com/pnpm/pnpm.github.io/pull/312
