### ISSUE TITLE
Command line svgs in docs

### ISSUE THREAD

**Issue by eighty4** [pnpm/pnpm.github.io#400]
Hi - I'm curious and not sure where else to ask this question: how are the cli svgs in the docs generated? Appreciate the help.

- Adam

**Comment by zkochan** [comment]
You mean this one? https://pnpm.io/cli/install

As far as I remember I recorded it with asciinema
https://asciinema.org/

and then there is some tool that can convert asciinema to svg. But I don't  remember what tool was it.

**Comment by eighty4** [comment]
Thanks (and sorry I could've Googled that)
