### ISSUE TITLE
False Gif for pnpm add command

### ISSUE THREAD

**Issue by EL-MTN** [pnpm/pnpm.github.io#74]
Page: https://pnpm.js.org/en/cli/add

It seems like the gif is showing a command for ```pnpm install``` instead of ```pnpm add```. I know it is only a small issue, but wouldn't it be great to fix so nobody like me will get confused?

**Comment by zkochan** [comment]
it was pretty hard to generate that Gif. I don't remember the steps. Would be easier to remove it

**Comment by EL-MTN** [comment]
The decisions should be up to you. I was just a bit confused with why the command was there at first glance. I know it is only a minor issue, but thanks for the attention.

**Comment by zkochan** [comment]
deleted
