### ISSUE TITLE
Whenever you refresh a page, it gives you old/broken links

### ISSUE THREAD

**Issue by risaddex** [pnpm/pnpm.github.io#94]
Steps to reproduce: 

1. Open an arbitrary link: IE  [https://pnpm.js.org/workspaces/](url)
2. The links are pointed to the correct path: https://pnpm.js.org/pnpm-workspace_yaml
3. refresh the page
4. The links are pointed to some old path or so: https://pnpm.js.org/pnpm-workspace_yaml/workspaces
5. The patter is that , whenever you refresh the page `/foo/bar` becomes `/foo/OLDBAR/bar`, resulting in 404 error.

cause (?)

Probably  some static chunk is getting fetched on refresh

**Comment by zkochan** [comment]
something is redirecting the pages to pages with trailing slash. As a result, the relative references are getting broken
